language: python
python:
  - 3.5

before_install:
    # update aptitude
    - sudo apt-get update

    # help python importing cv and/or cv2
    - python -m pip install -U pip
    - pip install opencv-python

script:
    # finally run tests
    - python -c "import os; import numpy; import cv2; print(os.path.dirname(cv2.__file__))"
