language: python
python:
  - 2.7

before_install:
    # update aptitude
    - sudo apt-get update

    # help python importing cv and/or cv2
    - python -m pip install -U pip

install:
    - pip install python-opencv

script:
    # finally run tests
    - python -c "import os; import numpy; import cv; import cv2; print(os.path.dirname(cv2.__file__))"
virtualenv:
    system_site_packages: true
