language: python

before_install:
# - sudo apt-get install opencv-python -y
install:
  # - "pip install --pre -r requirements.txt"
 - pip install opencv-python

python:
    - 3.5
script:
    # finally run tests
    - python -c "import os; import numpy; import cv2; print(os.path.dirname(cv2.__file__))"
