language: python

before_install:
 - sudo apt-get update
 - sudo apt-get install python-opencv
 - sudo dpkg -L python-opencv
install:
  # - "pip install --pre -r requirements.txt"

python:
    - "2.7"
script:
    # finally run tests
    - python -c "import os; import numpy; import cv2; print(os.path.dirname(cv2.__file__))"
